# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMAppClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMAppClip
	pod 'Alamofire'
  	pod 'AlamofireImage'
end

target 'MVVMWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMWidgetExtension
	pod 'Alamofire'
  	pod 'AlamofireImage'
end

target 'MVVMProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMProject
pod 'Alamofire'
  pod 'AlamofireImage'

  target 'MVVMProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMProjectUITests' do
    # Pods for testing
  end

end
